# Generated by Django 5.1.6 on 2025-02-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0005_alter_book_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=80)),
                ("postal_code", models.CharField(max_length=5)),
                ("city", models.CharField(max_length=50)),
            ],
        ),
    ]
