# Generated by Django 5.1.6 on 2025-02-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0007_author_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=8)),
                ("code", models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Address Entries"},
        ),
        migrations.AddField(
            model_name="book",
            name="published_countries",
            field=models.ManyToManyField(to="book_outlet.country"),
        ),
    ]
